// Demo product catalog — replace with your own products.
// `art` describes the generated thumbnail: gradient colors + decorative emoji.

const CATEGORIES = [
  "All",
  "Wallpapers",
  "App Icons",
  "Phone Themes",
  "Wallpaper Bundles",
  "Planners",
  "Wall Art",
];

const PRODUCTS = [
  {
    id: "starry-night-walls",
    name: "Starry Night Wallpaper Pack",
    category: "Wallpapers",
    price: 4.99,
    oldPrice: 7.99,
    rating: 4.9,
    reviews: 312,
    bestseller: true,
    art: { from: "#2b2d5e", to: "#7b6cf6", emoji: "🌌" },
    desc: "A dreamy set of 12 starry-night phone wallpapers in deep indigo and soft lilac tones. 4K resolution, sized for iPhone & Android.",
    includes: ["12 wallpapers (4K, 9:16)", "iOS & Android sizes", "Bonus lock-screen variants"],
  },
  {
    id: "cozy-icons",
    name: "Cozy Autumn App Icons (120 icons)",
    category: "App Icons",
    price: 6.5,
    oldPrice: 9.99,
    rating: 5.0,
    reviews: 208,
    bestseller: true,
    art: { from: "#b45f3c", to: "#f2c98a", emoji: "🍂" },
    desc: "120 hand-drawn cozy autumn app icons — warm browns, soft creams and little pumpkins. Covers all popular apps.",
    includes: ["120 app icons (PNG)", "Setup guide for iOS & Android", "3 matching wallpapers"],
  },
  {
    id: "celestial-theme",
    name: "Celestial Witchcore Phone Theme",
    category: "Phone Themes",
    price: 8.99,
    oldPrice: 12.99,
    rating: 4.8,
    reviews: 176,
    bestseller: false,
    art: { from: "#1d1b3a", to: "#8e5ff0", emoji: "🔮" },
    desc: "Complete phone makeover: moons, stars and potion vibes. Icons + wallpapers + widget covers, all matching.",
    includes: ["150 app icons", "8 wallpapers", "20 widget covers", "Setup video guide"],
  },
  {
    id: "minimal-beige-walls",
    name: "Minimalist Beige Wallpaper Set",
    category: "Wallpapers",
    price: 3.99,
    oldPrice: null,
    rating: 4.7,
    reviews: 145,
    bestseller: false,
    art: { from: "#d9c7b2", to: "#f5ede2", emoji: "🤍" },
    desc: "Clean, calm and classy — 10 minimalist beige & cream wallpapers for a clutter-free home screen.",
    includes: ["10 wallpapers (4K)", "Light & dark variants"],
  },
  {
    id: "retro-gameboy",
    name: "Retro Pixel Gameboy Wallpapers",
    category: "Wallpapers",
    price: 4.5,
    oldPrice: 5.99,
    rating: 4.8,
    reviews: 231,
    bestseller: true,
    art: { from: "#2e6e4e", to: "#a8e6b0", emoji: "🕹️" },
    desc: "Nostalgic pixel-art wallpapers inspired by retro handheld games. 15 designs in classic green & modern neon.",
    includes: ["15 pixel wallpapers", "Animated versions (Live)", "iOS & Android"],
  },
  {
    id: "ghibli-cottage-theme",
    name: "Cozy Cottage Anime Theme Pack",
    category: "Phone Themes",
    price: 9.99,
    oldPrice: 14.99,
    rating: 5.0,
    reviews: 389,
    bestseller: true,
    art: { from: "#4a7c59", to: "#cdeac0", emoji: "🏡" },
    desc: "A whimsical cottage-core anime-inspired theme: greenery, flowers and magic-shop vibes for your whole home screen.",
    includes: ["180 app icons", "10 wallpapers", "Widget covers", "Setup guide"],
  },
  {
    id: "digital-planner-2026",
    name: "2026 Digital Planner (GoodNotes)",
    category: "Planners",
    price: 7.99,
    oldPrice: 11.99,
    rating: 4.9,
    reviews: 267,
    bestseller: true,
    art: { from: "#c98bb9", to: "#f6dff1", emoji: "📒" },
    desc: "Fully hyperlinked 2026 digital planner — daily, weekly and monthly pages, habit trackers, budget sheets and more.",
    includes: ["365+ pages, hyperlinked", "GoodNotes / Notability / PDF", "500 bonus stickers"],
  },
  {
    id: "budget-organizer",
    name: "Budget & Finance Organizer",
    category: "Planners",
    price: 5.5,
    oldPrice: null,
    rating: 4.6,
    reviews: 98,
    bestseller: false,
    art: { from: "#3b6e8f", to: "#bfe3f0", emoji: "💰" },
    desc: "Take control of your money — monthly budget sheets, savings trackers, debt payoff pages and expense logs.",
    includes: ["40-page PDF", "Printable A4 & Letter", "iPad-friendly version"],
  },
  {
    id: "ocean-live-walls",
    name: "Ocean Waves Live Wallpapers",
    category: "Wallpapers",
    price: 5.99,
    oldPrice: 8.99,
    rating: 4.7,
    reviews: 121,
    bestseller: false,
    art: { from: "#155e75", to: "#7dd3fc", emoji: "🌊" },
    desc: "Gently moving ocean waves as live wallpapers — calm your screen with 8 soothing animated designs.",
    includes: ["8 live wallpapers", "Static versions included", "iPhone & Android"],
  },
  {
    id: "pastel-icons",
    name: "Pastel Dream App Icons (150 icons)",
    category: "App Icons",
    price: 6.99,
    oldPrice: 9.5,
    rating: 4.9,
    reviews: 342,
    bestseller: true,
    art: { from: "#f3a6c0", to: "#fde7f0", emoji: "🌸" },
    desc: "Soft pastel pink, lavender and baby blue icons for the dreamiest home screen ever. 150 popular apps covered.",
    includes: ["150 icons in 3 colorways", "Matching wallpapers", "Setup guide"],
  },
  {
    id: "dark-academia-art",
    name: "Dark Academia Gallery Wall Set",
    category: "Wall Art",
    price: 6.0,
    oldPrice: 8.0,
    rating: 4.8,
    reviews: 87,
    bestseller: false,
    art: { from: "#3f3126", to: "#a68a64", emoji: "📜" },
    desc: "Printable gallery wall set of 10 dark academia artworks — vintage sketches, moody tones and literary quotes.",
    includes: ["10 printable artworks", "Multiple print sizes", "High-res 300 DPI"],
  },
  {
    id: "botanical-art",
    name: "Botanical Printable Wall Art",
    category: "Wall Art",
    price: 4.25,
    oldPrice: null,
    rating: 4.7,
    reviews: 64,
    bestseller: false,
    art: { from: "#52796f", to: "#cad2c5", emoji: "🌿" },
    desc: "Fresh botanical prints for a calm, natural home — 8 hand-illustrated leafy artworks ready to print.",
    includes: ["8 printable artworks", "A4, A3, Letter sizes", "Instant download"],
  },
  {
    id: "mega-bundle",
    name: "Whole Shop Mega Bundle",
    category: "Wallpaper Bundles",
    price: 24.99,
    oldPrice: 49.99,
    rating: 5.0,
    reviews: 156,
    bestseller: true,
    art: { from: "#7c3aed", to: "#fbbf24", emoji: "🎁" },
    desc: "Everything in the shop, one magical price — every wallpaper, icon pack, theme and planner. Best value!",
    includes: ["All current products", "Free future updates", "Save over 50%"],
  },
  {
    id: "summer-beach-walls",
    name: "Summer Beach Wallpaper Bundle",
    category: "Wallpaper Bundles",
    price: 9.99,
    oldPrice: 15.99,
    rating: 4.6,
    reviews: 73,
    bestseller: false,
    art: { from: "#f59e0b", to: "#fef3c7", emoji: "🏖️" },
    desc: "30 sunny beach wallpapers — golden sands, palm trees and sunset skies to keep summer on your screen.",
    includes: ["30 wallpapers (4K)", "5 live wallpapers", "iOS & Android"],
  },
  {
    id: "cute-animal-walls",
    name: "Cute Animal Doodle Wallpapers",
    category: "Wallpapers",
    price: 3.5,
    oldPrice: 4.99,
    rating: 4.9,
    reviews: 189,
    bestseller: false,
    art: { from: "#f97393", to: "#ffe0ea", emoji: "🐰" },
    desc: "Adorable hand-doodled animal wallpapers — bunnies, cats and bears in the softest pastel palettes.",
    includes: ["12 wallpapers", "Matching lock screens"],
  },
  {
    id: "lofi-theme",
    name: "Lo-Fi Retro Study Theme",
    category: "Phone Themes",
    price: 8.5,
    oldPrice: 11.0,
    rating: 4.8,
    reviews: 143,
    bestseller: false,
    art: { from: "#5b4b8a", to: "#f0a6ca", emoji: "🎧" },
    desc: "Chill lo-fi vibes for your phone — warm sunset gradients, retro tape decks and cozy study-corner art.",
    includes: ["130 app icons", "8 wallpapers", "Widget covers"],
  },
  {
    id: "student-planner",
    name: "Student Study Planner",
    category: "Planners",
    price: 4.99,
    oldPrice: 6.99,
    rating: 4.7,
    reviews: 112,
    bestseller: false,
    art: { from: "#2563eb", to: "#bfdbfe", emoji: "🎓" },
    desc: "Ace your semester — class schedules, assignment trackers, exam countdowns and grade logs in one planner.",
    includes: ["60-page planner", "GoodNotes & PDF", "Printable version"],
  },
  {
    id: "moon-phases-art",
    name: "Moon Phases Wall Art Print",
    category: "Wall Art",
    price: 3.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 55,
    bestseller: false,
    art: { from: "#0f172a", to: "#94a3b8", emoji: "🌙" },
    desc: "An elegant moon-phase print in gold on midnight navy — perfect above a bed or reading nook.",
    includes: ["1 artwork, 6 sizes", "Gold & silver versions", "300 DPI print-ready"],
  },
];
